/**
 * Domain Event Constants for EventSphere.
 */

const DOMAIN_EVENTS = {
  // Event Lifecycle
  EVENT_CREATED: 'EVENT_CREATED',
  EVENT_PUBLISHED: 'EVENT_PUBLISHED',
  EVENT_UPDATED: 'EVENT_UPDATED',
  EVENT_CANCELLED: 'EVENT_CANCELLED',
  EVENT_ARCHIVED: 'EVENT_ARCHIVED',

  // Booking Lifecycle
  BOOKING_CREATED: 'BOOKING_CREATED',
  BOOKING_CONFIRMED: 'BOOKING_CONFIRMED',
  BOOKING_CANCELLED: 'BOOKING_CANCELLED',
  BOOKING_EXPIRED: 'BOOKING_EXPIRED',

  // Payment Lifecycle
  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
  PAYMENT_FAILED: 'PAYMENT_FAILED',

  // Ticketing Lifecycle
  TICKET_CREATED: 'TICKET_CREATED',
  TICKET_SCANNED: 'TICKET_SCANNED',
};

module.exports = DOMAIN_EVENTS;
